---
title: "GBM"
author: "Qian Shi (qs2164)"
date: "10/25/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if(!require(gbm)){
  install.packages('gbm')
  library('gb,')
}
```

#### Step 1: Processing the data 
```{r}
train_img <- readRDS("../output/training.RData")
test_img <- readRDS("../output/testing.RData")

train_label <- train_img[ , "y"]
train_img <- train_img[ ,!(colnames(train_img) %in% c("y"))]
test_label<- test_img[ ,"y"]
test_img <- test_img[ , !(colnames(test_img) %in% c("y"))]
```

#### Step 2: Just try a GBM model
```{r}
gbm_Model<- gbm(train_label~., data=train_img,
                n.trees=500,
                interaction.depth=1,
                shrinkage=0.2,
                distribution='multinomial')
gbm_predict<- as.data.frame(predict.gbm(gbm_Model, test_img, 
                                        n.trees=gbm_Model$n.trees, type='response'))
pred<- apply(gbm_predict, 1, which.max)
pred<- pred - 1
acu<- sum(pred == test_label)/length(test_label)   # Accuracy rate
acu
```

#### Step 3: Find the best parameters (by Cross Validation)
```{r}
# K-fold
K<- 3
n<- dim(train_img)[1]
folds<- sample(rep(1:K, each=n/K))

# Training parameters
trees_num<- seq(200, 800, 200)
inter_depth<- seq(1, 3, 1)
shrinks<- seq(0.01, 0.03, 0.01)
```


```{r}
# 1st fold 
train1<- train_img[folds != 1, ]
validate1<- train_img[folds == 1,]
train1_lab<- train_label[folds != 1]
validate1_lab<- train_label[folds == 1]

acu_list_1<-list()
for(i in 1:length(inter_depth)){
  acu_list_1[[i]]<- matrix(NA, ncol=length(trees_num), nrow=length(shrinks))
  colnames(acu_list_1[[i]])<- trees_num
  rownames(acu_list_1[[i]])<- shrinks
}

for(i in 1:length(inter_depth)){
  acu_mat<- acu_list_1[[i]]
  for(j in 1:length(shrinks)){
    for(k in 1:length(trees_num)){
      gbm_Fit<- gbm(train1_lab~., 
                    data=train1,
                    interaction.depth=inter_depth[i],
                    shrinkage=shrinks[j],
                    n.trees=trees_num[k],
                    distribution='multinomial')
      gbm_pred<- as.data.frame(predict.gbm(gbm_Fit, validate1,
                                              n.trees=gbm_Fit$n.trees, type='response'))
      pred_label<- apply(gbm_pred, 1, which.max)
      pred_label<- pred_label - 1
      acu_mat[j, k]<- sum(pred_label == validate1_lab) / length(validate1_lab)
    }
  }
  acu_list_1[[i]]<- acu_mat
}
names(acu_list_1)<- inter_depth
acu_list_1
```

```{r}
# 2nd fold
train2<- train_img[folds != 2, ]
validate2<- train_img[folds == 2,]
train2_lab<- train_label[folds != 2]
validate2_lab<- train_label[folds == 2]

acu_list_2<-list()
for(i in 1:length(inter_depth)){
  acu_list_2[[i]]<- matrix(NA, ncol=length(trees_num), nrow=length(shrinks))
  colnames(acu_list_2[[i]])<- trees_num
  rownames(acu_list_2[[i]])<- shrinks
}

for(i in 1:length(inter_depth)){
  acu_mat<- acu_list_2[[i]]
  for(j in 1:length(shrinks)){
    for(k in 1:length(trees_num)){
      gbm_Fit<- gbm(train2_lab~., 
                    data=train2,
                    interaction.depth=inter_depth[i],
                    shrinkage=shrinks[j],
                    n.trees=trees_num[k],
                    distribution='multinomial')
      gbm_pred<- as.data.frame(predict.gbm(gbm_Fit, validate2,
                                              n.trees=gbm_Fit$n.trees, type='response'))
      pred_label<- apply(gbm_pred, 1, which.max)
      pred_label<- pred_label - 1
      acu_mat[j, k]<- sum(pred_label == validate2_lab) / length(validate2_lab)
    }
  }
  acu_list_2[[i]]<- acu_mat
}
names(acu_list_2)<- inter_depth
acu_list_2
```

```{r}
# 3rd fold
train3<- train_img[folds != 3, ]
validate3<- train_img[folds == 3,]
train3_lab<- train_label[folds != 3]
validate3_lab<- train_label[folds == 3]

acu_list_3<-list()
for(i in 1:length(inter_depth)){
  acu_list_3[[i]]<- matrix(NA, ncol=length(trees_num), nrow=length(shrinks))
  colnames(acu_list_3[[i]])<- trees_num
  rownames(acu_list_3[[i]])<- shrinks
}

for(i in 1:length(inter_depth)){
  acu_mat<- acu_list_3[[i]]
  for(j in 1:length(shrinks)){
    for(k in 1:length(trees_num)){
      gbm_Fit<- gbm(train3_lab~., 
                    data=train3,
                    interaction.depth=inter_depth[i],
                    shrinkage=shrinks[j],
                    n.trees=trees_num[k],
                    distribution='multinomial')
      gbm_pred<- as.data.frame(predict.gbm(gbm_Fit, validate3,
                                              n.trees=gbm_Fit$n.trees, type='response'))
      pred_label<- apply(gbm_pred, 1, which.max)
      pred_label<- pred_label - 1
      acu_mat[j, k]<- sum(pred_label == validate3_lab) / length(validate3_lab)
    }
  }
  acu_list_3[[i]]<- acu_mat
}
names(acu_list_3)<- inter_depth
acu_list_3
```

```{r}
# Trees number vs Interdepth
trees_mat1<- sapply(acu_list_1, function(x){return(apply(x, 2, max))})
trees_mat2<- sapply(acu_list_2, function(x){return(apply(x, 2, max))})
trees_mat3<- sapply(acu_list_3, function(x){return(apply(x, 2, max))})

plot(trees_num, trees_mat1[,1], type='b', col='red', ylim=c(0.77, 0.83), ylab='Accuracy', xlab='Number of trees')
lines(trees_num, trees_mat2[,1], type='b', col='red')
lines(trees_num, trees_mat3[,1], type='b', col='red')

lines(trees_num, trees_mat1[,2], type='b', col='green')
lines(trees_num, trees_mat2[,2], type='b', col='green')
lines(trees_num, trees_mat3[,2], type='b', col='green')

lines(trees_num, trees_mat1[,3], type='b', col='blue')
lines(trees_num, trees_mat2[,3], type='b', col='blue')
lines(trees_num, trees_mat3[,3], type='b', col='blue')
legend("bottomright", paste("Interdepth = ", inter_depth), col=c('red', 'green', 'blue'), lty=1, cex=0.6)
```

```{r}
# Shrinkage vs Interdepth
shrink_mat1<- sapply(acu_list_1, function(x){return(apply(x, 1, max))})
shrink_mat2<- sapply(acu_list_2, function(x){return(apply(x, 1, max))})
shrink_mat3<- sapply(acu_list_3, function(x){return(apply(x, 1, max))})

plot(shrinks, shrink_mat1[,1], type='b', col='red', ylim=c(0.785, 0.825), ylab='Accuracy', xlab='Shrinkage')
lines(shrinks, shrink_mat2[,1], type='b', col='red')
lines(shrinks, shrink_mat3[,1], type='b', col='red')

lines(shrinks, shrink_mat1[,2], type='b', col='green')
lines(shrinks, shrink_mat2[,2], type='b', col='green')
lines(shrinks, shrink_mat3[,2], type='b', col='green')

lines(shrinks, shrink_mat1[,3], type='b', col='blue')
lines(shrinks, shrink_mat2[,3], type='b', col='blue')
lines(shrinks, shrink_mat3[,3], type='b', col='blue')
legend("bottomright", paste("Interdepth = ", inter_depth), col=c('red', 'green', 'blue'), lty=1, cex=0.6)
```

From the plots show above, to avoid overfitting, the best model perhaps is: 
   Interdepth = 3, 
   Shrinkage = 0.02,
   Trees = 600



